#Version represents which version of yaml file we are using
version: "3"
services:
  #Here "selenium-hub" is a service name
  selenium-hub:
    image: selenium/hub:latest
    container_name: sel-hub
    restart: always
    ports:
      - "4444:4444"
  
  #To create a chrome container with latest version
  #Here "chrome" is a service name
  chrome:
    image: selenium/node-chrome-debug:latest
    volumes: 
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=sel-hub
      - HUB_PORT=4444
    restart: on-failure:3
  
  #To create a firefox container with latest version
  #Here "firefox" is a service name
  firefox:
    image: selenium/node-firefox-debug:latest
    volumes: 
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=sel-hub
      - HUB_PORT=4444
    restart: on-failure:3